version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://example:example@postgres:5432/example
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  db-data:
